### PR TITLE
Issue 13

### LINKED ISSUE #13: Add new issue templates
We need new issue templates for each issue type.

### PR DESCRIPTION
**Pull request by nvisionative**
Resolves #13

### CODE REVIEW

**Comment by EPTamminga** [comment]
A simpler solution for the debug DLL’s is just to copy the files to the bin folder of the site and overwrite the existing dll. If needed, we could make it a ‘normal’ install pack
To remove the debug dll, just reinstall the module with the original install pack

**Comment by EPTamminga** [comment]
@valadas I have made such a descriotion before. They do not need the log if the error is displayed on screen. In general, if people know how to install modules, they probably know where the log is? But we could make some documentation about that and put it in a general wiki and point to that from the issue text.

**Comment by valadas** [comment]
Agrred

**Comment by valadas** [comment]
Agreed I mean

**Comment by nvisionative** [comment]
Excellent - shall I go ahead and merge this request?

**Pull request merged**
